/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { RoadmapOutput } from "../../../server/modules/ai/ai.service";
import WeeklyTimeline from "./WeeklyTimeline";
import RecommendationCards from "./RecommendationCards";
import Card, { CardBody, CardHeader } from "../Card";
import Button from "../Button";
import {
  Copy,
  Download,
  Bookmark,
  RefreshCw,
  Award,
  Clock,
  Heart,
  Terminal,
  FileText,
} from "lucide-react";
import toast from "react-hot-toast";

interface RoadmapResultProps {
  id?: string;
  roadmap: RoadmapOutput;
  onReset: () => void;
  onSave: () => void;
  isSaved: boolean;
}

export default function RoadmapResult({
  id,
  roadmap,
  onReset,
  onSave,
  isSaved,
}: RoadmapResultProps) {
  const handleCopyText = async () => {
    try {
      const formattedText = `
=== Personal AI Learning Roadmap: ${roadmap.title} ===
Duration: ${roadmap.estimatedDuration} | Difficulty: ${roadmap.difficulty}

--- WEEKLY STUDY SYLLABUS ---
${roadmap.weeklyPlan
  .map(
    (w) => `
Week ${w.week}: ${w.goal}
- Topics: ${w.topics.join(", ")}
- Projects: ${w.projects.join(", ")}`
  )
  .join("\n")}

--- SUPPLEMENTAL ROADMAP SUGGESTIONS ---
${roadmap.recommendedLearningPaths.map((p) => `- ${p}`).join("\n")}

--- SENIOR MENTOR PRO TIPS ---
${roadmap.tips.map((t) => `- ${t}`).join("\n")}
      `.trim();

      await navigator.clipboard.writeText(formattedText);
      toast.success("Roadmap copied to clipboard!");
    } catch (err) {
      toast.error("Failed to copy roadmap to clipboard.");
    }
  };

  const handleDownloadPDF = () => {
    // Generate a beautiful standalone HTML print report that browsers easily print or save as PDF
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${roadmap.title} - AI Learning Roadmap</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      line-height: 1.6;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
    }
    h1 {
      color: #0f172a;
      font-size: 28px;
      margin-bottom: 5px;
      border-bottom: 2px solid #4f46e5;
      padding-bottom: 10px;
    }
    .meta {
      font-size: 14px;
      color: #64748b;
      margin-bottom: 30px;
      font-family: monospace;
    }
    .meta span {
      margin-right: 20px;
      font-weight: bold;
    }
    .section-title {
      font-size: 18px;
      color: #4f46e5;
      margin-top: 40px;
      margin-bottom: 15px;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 5px;
    }
    .week-card {
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 15px;
      background: #f8fafc;
    }
    .week-header {
      display: flex;
      justify-content: space-between;
      margin-bottom: 10px;
    }
    .week-num {
      background: #e0e7ff;
      color: #3730a3;
      padding: 2px 8px;
      font-size: 12px;
      border-radius: 4px;
      font-weight: bold;
    }
    .week-goal {
      font-weight: bold;
      color: #0f172a;
    }
    ul {
      margin: 5px 0 0 20px;
      padding: 0;
    }
    li {
      margin-bottom: 5px;
      font-size: 13px;
    }
    .project-box {
      margin-top: 10px;
      padding: 10px;
      background: #f1f5f9;
      border-radius: 6px;
      font-size: 12px;
      border-left: 3px solid #4f46e5;
    }
    .print-btn {
      background: #4f46e5;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 6px;
      font-weight: bold;
      cursor: pointer;
      margin-bottom: 20px;
    }
    @media print {
      .print-btn { display: none; }
      body { margin: 20px; }
    }
  </style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">Print or Save as PDF</button>
  <h1>${roadmap.title}</h1>
  <div class="meta">
    <span>ESTIMATED DURATION: ${roadmap.estimatedDuration}</span>
    <span>DIFFICULTY: ${roadmap.difficulty}</span>
    <span>GENERATED BY: SkillPilot AI</span>
  </div>

  <div class="section-title">Weekly Syllabus Milestones</div>
  ${roadmap.weeklyPlan
    .map(
      (w) => `
    <div class="week-card">
      <div class="week-header">
        <span class="week-goal">${w.goal}</span>
        <span class="week-num">Week ${w.week}</span>
      </div>
      <div><strong>Core Topics:</strong></div>
      <ul>
        ${w.topics.map((t) => `<li>${t}</li>`).join("")}
      </ul>
      ${
        w.projects && w.projects.length > 0
          ? `
        <div class="project-box">
          <strong>Lab Challenge:</strong> ${w.projects.join(" | ")}
        </div>
      `
          : ""
      }
    </div>
  `
    )
    .join("")}

  <div class="section-title">Senior Mentor Guidance Tips</div>
  <ul>
    ${roadmap.tips.map((t) => `<li>${t}</li>`).join("")}
  </ul>

  <div class="section-title">Suggested Supplementary Modules</div>
  <ul>
    ${roadmap.recommendedLearningPaths.map((p) => `<li>${p}</li>`).join("")}
  </ul>
</body>
</html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${roadmap.title.replace(/\s+/g, "_")}_Roadmap.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("Printable Roadmap HTML downloaded! Open and select 'Print to PDF' to save.");
  };

  return (
    <div id={id} className="space-y-8 text-left animate-fade-in max-w-4xl mx-auto">
      {/* 1. Header Banner */}
      <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 md:p-8 border border-slate-800 shadow-md relative overflow-hidden">
        {/* Neon decorative layout */}
        <div className="absolute -right-16 -top-16 w-48 h-48 rounded-full bg-brand-500/10 blur-3xl pointer-events-none" />
        <div className="absolute -left-16 -bottom-16 w-48 h-48 rounded-full bg-indigo-500/10 blur-3xl pointer-events-none" />

        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6">
          <div className="min-w-0">
            <span className="text-[10px] font-bold font-mono text-brand-400 uppercase tracking-widest block">
              Operator Career Blueprint
            </span>
            <h1 className="text-xl sm:text-2xl md:text-3xl font-extrabold tracking-tight mt-1 truncate">
              {roadmap.title}
            </h1>
            <p className="text-slate-400 text-xs mt-1.5 flex items-center gap-1">
              <Terminal className="h-3.5 w-3.5" /> Customized by SkillPilot Agentic Core
            </p>
          </div>

          {/* Quick Stats */}
          <div className="flex gap-4 shrink-0 font-mono text-xs">
            <div className="px-4.5 py-2.5 bg-slate-950/60 border border-slate-800 rounded-xl">
              <span className="text-slate-500 uppercase font-bold text-[9px] tracking-wider block">
                Duration
              </span>
              <span className="text-brand-300 font-extrabold mt-0.5 flex items-center gap-1.5">
                <Clock className="h-3.5 w-3.5" /> {roadmap.estimatedDuration}
              </span>
            </div>
            <div className="px-4.5 py-2.5 bg-slate-950/60 border border-slate-800 rounded-xl">
              <span className="text-slate-500 uppercase font-bold text-[9px] tracking-wider block">
                Difficulty
              </span>
              <span className="text-indigo-300 font-extrabold mt-0.5 flex items-center gap-1.5">
                <Award className="h-3.5 w-3.5" /> {roadmap.difficulty}
              </span>
            </div>
          </div>
        </div>

        {/* Toolbar Button Controls */}
        <div className="mt-8 pt-6 border-t border-slate-800 flex flex-wrap gap-3">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyText}
            className="bg-slate-800 hover:bg-slate-750 text-slate-100 border-slate-700 text-xs font-bold"
            leftIcon={<Copy className="h-3.5 w-3.5" />}
          >
            Copy Text
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadPDF}
            className="bg-slate-800 hover:bg-slate-750 text-slate-100 border-slate-700 text-xs font-bold"
            leftIcon={<Download className="h-3.5 w-3.5" />}
          >
            Download PDF
          </Button>

          <Button
            variant={isSaved ? "secondary" : "outline"}
            size="sm"
            onClick={onSave}
            className={`text-xs font-bold ${
              isSaved
                ? "bg-emerald-50 border-emerald-200 text-emerald-700 hover:bg-emerald-100"
                : "bg-slate-800 hover:bg-slate-750 text-slate-100 border-slate-700"
            }`}
            leftIcon={<Bookmark className={`h-3.5 w-3.5 ${isSaved ? "fill-emerald-600" : ""}`} />}
          >
            {isSaved ? "Saved Locally" : "Save Locally"}
          </Button>

          <div className="flex-grow" />

          <Button
            variant="ghost"
            size="sm"
            onClick={onReset}
            className="text-slate-400 hover:text-slate-200 text-xs font-bold font-mono"
            leftIcon={<RefreshCw className="h-3.5 w-3.5" />}
          >
            Configure New Goal
          </Button>
        </div>
      </div>

      {/* 2. Mentor advice Block */}
      <Card className="border border-slate-200 bg-slate-50/30 overflow-hidden">
        <CardHeader className="border-b border-slate-100 bg-slate-50/50 py-4.5">
          <h3 className="text-xs font-bold font-mono text-slate-400 uppercase tracking-widest flex items-center gap-1.5">
            <Heart className="h-4 w-4 text-rose-500 fill-rose-500/10" /> Senior Career Advice Vector
          </h3>
        </CardHeader>
        <CardBody className="p-6 space-y-3 text-slate-600 text-xs sm:text-sm italic leading-relaxed font-medium">
          {roadmap.tips.map((tip, index) => (
            <div key={index} className="flex gap-3">
              <span className="text-brand-600 text-lg font-bold select-none shrink-0 font-mono">
                “
              </span>
              <p className="flex-grow text-slate-700">{tip}</p>
            </div>
          ))}
        </CardBody>
      </Card>

      {/* 3. Main Weekly Timeline */}
      <div className="pt-2">
        <WeeklyTimeline plan={roadmap.weeklyPlan} />
      </div>

      {/* 4. Recommendation Cards */}
      <div className="pt-2 border-t border-slate-100">
        <RecommendationCards recommendations={roadmap.recommendedLearningPaths} />
      </div>
    </div>
  );
}
